### ISSUE TITLE
test.txt:1-1: This is a simple puzzle

### ISSUE THREAD

**Issue by 0pdd** [yegor256/kill-me#1]
The puzzle `1-3675a896` (from #1) in [`test.txt`](https://github.com/yegor256/kill-me/blob/master/test.txt) (lines 1-1) has to be resolved: "This is a simple puzzle"

The puzzle was created by Yegor Bugayenko on 06-Nov-17. 

Estimate: 15 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
I'm not managing ` yegor256/kill-me ` GitHub repository. You have to contact me in Slack first. Our [policy](http://datum.zerocracy.com/pages/policy.html) explains how.
