### ISSUE TITLE
test.txt:3-3: Some more puzzle here

### ISSUE THREAD

**Issue by 0pdd** [yegor256/kill-me#9]
The puzzle `2-dbc47f70` (from #2) in [`test.txt`](https://github.com/yegor256/kill-me/blob/master/test.txt) (lines 3-3) has to be resolved: "Some more puzzle here"

The puzzle was created by Yegor Bugayenko on 04-Dec-17. 

Estimate: 25 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@0pdd I'm not managing this repo, remove the [webhook](https://github.com/yegor256/kill-me/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by 0pdd** [comment]
The puzzle `2-dbc47f70` has disappeared from the source code, that's why I closed this issue.
